# Generated by Django 5.1.4 on 2025-01-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=50)),
                ('Admin_email', models.CharField(max_length=50)),
                ('Admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
