# Generated by Django 5.1.4 on 2025-01-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_admin',
            old_name='Admin_email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='tbl_admin',
            old_name='Admin_name',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='tbl_admin',
            old_name='Admin_password',
            new_name='admin_password',
        ),
    ]
