# Generated by Django 5.1.4 on 2025-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='tbl_subtype',
            old_name='type',
            new_name='Type',
        ),
    ]
