# Generated by Django 5.1.4 on 2025-01-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_department_rename_type_tbl_subtype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=50)),
            ],
        ),
    ]
