# Generated by Django 5.1.4 on 2025-02-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter.tbl_product')),
            ],
        ),
    ]
