# Generated by Django 5.1.4 on 2025-02-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0004_tbl_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
