# Generated by Django 5.1.4 on 2025-02-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0005_delete_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.FileField(upload_to='Assets/File/renter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter.tbl_product')),
            ],
        ),
    ]
