# Generated by Django 5.1.4 on 2025-02-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0006_tbl_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Renter.tbl_product'),
        ),
    ]
