# Generated by Django 5.1.4 on 2025-02-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0007_alter_tbl_gallery_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
