# Generated by Django 5.1.4 on 2025-01-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_staff'),
        ('Guest', '0006_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_confirmpassword', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/File/user')),
                ('user_proof', models.FileField(upload_to='Assets/File/user')),
                ('user_district', models.CharField(max_length=50)),
                ('user_place', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
