# Generated by Django 5.1.4 on 2025-01-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_place',
        ),
    ]
