# Generated by Django 5.1.4 on 2025-02-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_tbl_renter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_renter',
            old_name='renter_logo',
            new_name='renter_photo',
        ),
    ]
