# Generated by Django 5.1.4 on 2025-02-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_rename_renter_logo_tbl_renter_renter_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_renter',
        ),
    ]
