# Generated by Django 5.1.4 on 2025-02-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_staff'),
        ('Guest', '0019_delete_tbl_renter'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=50)),
                ('renter_email', models.CharField(max_length=50)),
                ('renter_contact', models.CharField(max_length=50)),
                ('renter_address', models.CharField(max_length=50)),
                ('renter_password', models.CharField(max_length=50)),
                ('renter_status', models.IntegerField(max_length=50)),
                ('renter_photo', models.FileField(upload_to='Assets/Files/Renter')),
                ('renter_proof', models.FileField(upload_to='Assets/Files/Renter')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
