# Generated by Django 5.1.4 on 2025-02-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0020_tbl_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_renter',
            name='renter_status',
            field=models.IntegerField(default=0),
        ),
    ]
