# Generated by Django 5.1.4 on 2025-02-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='rating_value',
            field=models.IntegerField(default=0),
        ),
    ]
