# Generated by Django 5.1.4 on 2025-02-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_complaint_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.CharField(max_length=50),
        ),
    ]
