# Generated by Django 5.1.4 on 2025-02-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_tbl_complaint_complaint_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
