# Generated by Django 5.1.4 on 2025-02-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
