# Generated by Django 5.1.4 on 2025-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_fordate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_todate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
