# Generated by Django 5.1.4 on 2025-02-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_rename_repair_tbl_repair_repairshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
