# Generated by Django 5.1.4 on 2025-03-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_tbl_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
