# Generated by Django 5.1.4 on 2025-03-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0026_tbl_repairshop'),
        ('Renter', '0009_tbl_gallery'),
        ('User', '0029_remove_tbl_cart_booking_remove_tbl_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_amount', models.CharField(max_length=30)),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_fordate', models.DateField(null=True)),
                ('booking_todate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField(default=1)),
                ('cart_status', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter.tbl_product')),
            ],
        ),
    ]
