# Generated by Django 5.1.7 on 2025-03-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_tbl_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
